import { Copy, Maximize2, Sparkles } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { useState } from 'react';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import PromptHistory from './PromptHistory';

interface AgentOutputProps {
  prompt: string;
  summary: string;
  isPending: boolean;
}

const AgentOutput = ({ prompt, summary, isPending }: AgentOutputProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
    toast.success('Copied to clipboard');
  };

  if (!summary && !isPending) {
    return <PromptHistory />;
  }

  return (
    <div className="group relative flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white text-sm shadow-sm transition-all hover:shadow-md dark:border-zinc-800 dark:bg-zinc-950">
      <div className="p-4">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-2 text-zinc-500">
            AI Summary
          </div>

          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7 text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100"
              onClick={handleCopy}
              title="Copy to clipboard"
            >
              <Copy size={14} />
            </Button>

            <Dialog>
              <DialogTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-7 w-7 text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100"
                  title="Expand view"
                >
                  <Maximize2 size={14} />
                </Button>
              </DialogTrigger>
              <DialogContent className="max-h-[80vh] overflow-y-auto sm:max-w-2xl">
                <DialogHeader>
                  <DialogTitle className="mb-2 flex items-center gap-2  text-sm text-zinc-500">
                    Prompt:
                    <span className="text-zinc-900 dark:text-zinc-100">
                      {prompt}
                    </span>
                  </DialogTitle>
                  <DialogDescription className="whitespace-pre-wrap text-base text-zinc-800 dark:text-zinc-300">
                    {summary}
                  </DialogDescription>
                </DialogHeader>
                <DialogFooter className="gap-2 sm:justify-between">
                  <span className="text-xs text-zinc-400 self-center hidden sm:block">
                    Generated by Kelvin
                  </span>
                  <div className="flex gap-2">
                    <Button variant="secondary" onClick={handleCopy} size="sm">
                      <Copy className="mr-2 h-3 w-3" />
                      Copy
                    </Button>
                    <DialogClose asChild>
                      <Button variant="outline" size="sm">
                        Close
                      </Button>
                    </DialogClose>
                  </div>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>

        <div className="font-medium text-zinc-900 dark:text-zinc-100 py-0.5">
          {prompt}
        </div>

        {isPending ? (
          <div className="space-y-2 py-1">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-[90%]" />
            <Skeleton className="h-4 w-[80%]" />
          </div>
        ) : (
          <div className="relative">
            <p className="line-clamp-4 leading-relaxed text-zinc-600 dark:text-zinc-400">
              {summary}
            </p>

            {summary.length > 200 && (
              <div className="absolute bottom-0 left-0 right-0 h-6 bg-gradient-to-t from-white to-transparent dark:from-zinc-950"></div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default AgentOutput;
